# NumPy Arrays

In [1]:
import numpy as np

my_list = [1,2,3]
arr = np.array(my_list)
arr

array([1, 2, 3])

In [2]:
# 2D array 

my_mat = [[1,2,3],[4,5,6],[7,8,9]]
np.array(my_mat)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [3]:
# create an array sampled from 0 to 9
display(np.arange(0,10))

# create an array sampled from 0 to 9 with 2 steps
display(np.arange(0,11,2))

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

array([ 0,  2,  4,  6,  8, 10])

In [4]:
# create an array of 3 zeros
display(np.zeros(3))

# create an array of 5x5 matrix
display(np.zeros((5,5)))

array([0., 0., 0.])

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [5]:
# create an array of 10 ones
display(np.ones(4))

# create an 3x4 matrix of ones
display(np.ones((3,4)))

array([1., 1., 1., 1.])

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [6]:
# returns evenly spaced numbers over the specified interval
np.linspace(0,5,20)

array([0.        , 0.26315789, 0.52631579, 0.78947368, 1.05263158,
       1.31578947, 1.57894737, 1.84210526, 2.10526316, 2.36842105,
       2.63157895, 2.89473684, 3.15789474, 3.42105263, 3.68421053,
       3.94736842, 4.21052632, 4.47368421, 4.73684211, 5.        ])

In [7]:
# create a 4x4 identity matrix 
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [8]:
# create an array of 5 random numbers sampled from 0 to 1
display(np.random.rand(5))

# create an array of 5x4 random numbers matrix sampled from 0 to 1
display(np.random.rand(5,4))

# create an array of 5x4 random numbers matrix sampled from a standard normal distribution
display(np.random.randn(5,4))

array([0.19318685, 0.99189165, 0.62857664, 0.73713726, 0.76683473])

array([[0.11126448, 0.19608493, 0.98958555, 0.83815874],
       [0.42543453, 0.9837634 , 0.78111069, 0.86715262],
       [0.41605036, 0.01249577, 0.41511168, 0.39014004],
       [0.62683147, 0.65460129, 0.87811973, 0.40868302],
       [0.38137754, 0.91491103, 0.47690883, 0.58686958]])

array([[-1.19187768, -1.30222509, -1.02497304, -0.80733638],
       [ 1.63429809,  1.30018257,  0.44018255,  0.47484251],
       [ 0.01804011, -1.78242624, -1.21438256,  0.39509104],
       [-1.80855889, -0.56365371,  1.34775375,  0.73182611],
       [ 1.38727884,  0.63169485, -0.84580454, -0.6523204 ]])

In [9]:
# pick up the random number between 1 and 100 with 10 steps
np.random.randint(1,100,10)

array([15,  1, 28, 21, 91, 34, 54, 12, 38, 86])

In [10]:
# create a 5x5 matrix with vaules ranging from 0 to 25
arr = np.arange(25)
display(arr)

# reshape the array to a 5x5 matrix
display(arr.reshape(5,5))

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [11]:
# find the max value of an array
display(arr.max())

# find the min value of an array
display(arr.min())

# return the index of the max value
display(arr.argmax())

#return the type of an array
display(arr.dtype)

24

0

24

dtype('int64')

# NumPy Indexing and Selection

## Indexing in normal array

In [12]:
arr = np.arange(0,11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [13]:
arr[8]

8

In [14]:
arr[1:5]

array([1, 2, 3, 4])

In [15]:
arr[0:5]

array([0, 1, 2, 3, 4])

In [16]:
# grab everything beyond index 5 
arr[5:]

array([ 5,  6,  7,  8,  9, 10])

In [17]:
arr[0:5] = 100
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [18]:
arr = np.arange(0,11)
slice_of_arr = arr[0:6]
display(f'slice_of_arr: , {slice_of_arr}')

# if the slice_of_arr changed, the value of the original array will be changed as well
slice_of_arr[:] =20

display(f'slice_of_arr changed: {slice_of_arr}')
display(f'the original arr: {arr}')

'slice_of_arr: , [0 1 2 3 4 5]'

'slice_of_arr changed: [20 20 20 20 20 20]'

'the original arr: [20 20 20 20 20 20  6  7  8  9 10]'

In [19]:
# copy an array without affect the original array
arr_copy = arr.copy()
arr_copy

array([20, 20, 20, 20, 20, 20,  6,  7,  8,  9, 10])

## Indexing in 2D array

In [20]:
arr_2d = np.array([[2,4,6],[3,6,9],[5,10,15]])
arr_2d

array([[ 2,  4,  6],
       [ 3,  6,  9],
       [ 5, 10, 15]])

In [21]:
display(arr_2d[0])

# single element 
display(arr_2d[0][0])
display(arr_2d[0,0])

# grab everythin including row 0 and row 1 and grab everythin from the column 1 and all the way to the end 
display(arr_2d[:2,1:])

array([2, 4, 6])

2

2

array([[4, 6],
       [6, 9]])

## Conditional selection 


In [22]:
arr = np.arange(1,11)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [23]:
bool_arr = arr > 5 
bool_arr

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [24]:
arr[bool_arr]

array([ 6,  7,  8,  9, 10])

In [25]:
arr[arr > 5]

array([ 6,  7,  8,  9, 10])

# NumPy Operations

* Array with Array
* Array with Scalars
* Universal Array Functions

In [26]:
arr = np.arange(1,10)
arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [27]:
display(arr + arr)
display(arr - arr)
display(arr * arr)
display(arr - 100)
display(arr / 100)
display(arr ** 2)

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18])

array([0, 0, 0, 0, 0, 0, 0, 0, 0])

array([ 1,  4,  9, 16, 25, 36, 49, 64, 81])

array([-99, -98, -97, -96, -95, -94, -93, -92, -91])

array([0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09])

array([ 1,  4,  9, 16, 25, 36, 49, 64, 81])

In [28]:
# Universal Array Functions
display(np.sqrt(arr))
display(np.sin(arr))
display(np.max(arr))
display(np.exp(arr))

array([1.        , 1.41421356, 1.73205081, 2.        , 2.23606798,
       2.44948974, 2.64575131, 2.82842712, 3.        ])

array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 , -0.95892427,
       -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849])

9

array([2.71828183e+00, 7.38905610e+00, 2.00855369e+01, 5.45981500e+01,
       1.48413159e+02, 4.03428793e+02, 1.09663316e+03, 2.98095799e+03,
       8.10308393e+03])